var OPEN_SOURCE_LIBRARIES_PLATFORMS_REPOSITORY = [
  {
    "full_name": "angular/angular",
    "description": "One framework. Mobile \u0026 desktop.",
    "fork": false,
    "created_at": "2014-09-18T16:12:01.000Z",
    "updated_at": "2020-03-25T16:44:09.907Z",
    "pushed_at": "2020-03-25T16:40:20.000Z",
    "homepage": "https://angular.io",
    "size": 136115,
    "stargazers_count": 59214,
    "language": "TypeScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 16212,
    "mirror_url": null,
    "open_issues_count": 3318,
    "default_branch": "master",
    "subscribers_count": 3203,
    "uuid": "24195339",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 723,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-06-26T21:05:08.034Z",
    "rank": 27,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "24195339",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 723,
    "keywords": [
      "angular",
      "javascript",
      "pwa",
      "typescript",
      "web",
      "web-framework",
      "web-performance"
    ]
  },
  {
    "full_name": "reduxjs/react-redux",
    "description": "Official React bindings for Redux",
    "fork": false,
    "created_at": "2015-07-11T17:32:01.000Z",
    "updated_at": "2020-03-18T09:29:25.000Z",
    "pushed_at": "2020-03-17T17:46:22.000Z",
    "homepage": "https://react-redux.js.org",
    "size": 3373,
    "stargazers_count": 19111,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 2813,
    "mirror_url": null,
    "open_issues_count": 27,
    "default_branch": "master",
    "subscribers_count": 456,
    "uuid": "38934449",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 145,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE.md",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-04-12T20:47:06.321Z",
    "rank": 22,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "38934449",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 145,
    "keywords": [
      "react",
      "redux"
    ]
  },
  {
    "full_name": "immutable-js/immutable-js",
    "description": "Immutable persistent data collections for Javascript which increase efficiency and simplicity.",
    "fork": false,
    "created_at": "2014-07-02T06:02:29.000Z",
    "updated_at": "2020-03-17T02:15:06.000Z",
    "pushed_at": "2020-03-17T04:30:30.000Z",
    "homepage": "https://immutable-js.github.io/immutable-js/",
    "size": 21824,
    "stargazers_count": 29334,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 1702,
    "mirror_url": null,
    "open_issues_count": 170,
    "default_branch": "master",
    "subscribers_count": 578,
    "uuid": "21413198",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 173,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": null,
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2017-10-17T07:13:50.810Z",
    "rank": 21,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "21413198",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 173,
    "keywords": [

    ]
  },
  {
    "full_name": "jupyterlab/jupyterlab",
    "description": "JupyterLab computational environment.",
    "fork": false,
    "created_at": "2016-06-03T20:09:17.000Z",
    "updated_at": "2020-04-01T19:17:49.591Z",
    "pushed_at": "2020-04-01T18:30:49.000Z",
    "homepage": "https://jupyterlab.readthedocs.io/",
    "size": 85353,
    "stargazers_count": 9603,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 1558,
    "mirror_url": null,
    "open_issues_count": 1369,
    "default_branch": "master",
    "subscribers_count": 338,
    "uuid": "60374819",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 247,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-04-25T10:38:27.965Z",
    "rank": 19,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "60374819",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 247,
    "keywords": [
      "jupyterlab"
    ]
  },
  {
    "full_name": "apollographql/react-apollo",
    "description": ":recycle: React integration for Apollo Client",
    "fork": false,
    "created_at": "2016-04-13T23:14:51.000Z",
    "updated_at": "2020-04-03T08:36:27.000Z",
    "pushed_at": "2020-04-03T10:23:13.000Z",
    "homepage": "https://www.apollographql.com/docs/react/",
    "size": 15830,
    "stargazers_count": 6685,
    "language": "TypeScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 835,
    "mirror_url": null,
    "open_issues_count": 160,
    "default_branch": "master",
    "subscribers_count": 154,
    "uuid": "56192185",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 225,
    "has_readme": "README.md",
    "has_changelog": "Changelog.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-08-05T20:07:05.212Z",
    "rank": 19,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "56192185",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 225,
    "keywords": [
      "apollo",
      "graphql",
      "react",
      "redux",
      "ssr"
    ]
  },
  {
    "full_name": "aws-amplify/amplify-js",
    "description": "A declarative JavaScript library for application development using cloud services.",
    "fork": false,
    "created_at": "2017-10-02T22:17:14.000Z",
    "updated_at": "2020-04-03T02:17:10.409Z",
    "pushed_at": "2020-03-17T20:24:57.000Z",
    "homepage": "https://aws-amplify.github.io/",
    "size": 125619,
    "stargazers_count": 6590,
    "language": "TypeScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 1213,
    "mirror_url": null,
    "open_issues_count": 655,
    "default_branch": "master",
    "subscribers_count": 174,
    "uuid": "105590837",
    "source_name": null,
    "license": "Apache-2.0",
    "private": false,
    "contributions_count": 168,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": ".github/CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-05-14T15:45:14.588Z",
    "rank": 18,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "105590837",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 168,
    "keywords": [
      "amazon-cognito",
      "analytics",
      "aws",
      "aws-apigateway",
      "aws-cognito",
      "aws-mobile",
      "aws-mobilehub",
      "aws-s3",
      "cloud-service",
      "cognito",
      "javascript",
      "metrics",
      "mobile-analytics",
      "pinpoint",
      "pwa",
      "react",
      "react-native",
      "storage"
    ]
  },
  {
    "full_name": "babel/babel-preset-env",
    "description": "PSA: this repo has been moved into babel/babel --\u003e",
    "fork": false,
    "created_at": "2016-08-14T03:48:33.000Z",
    "updated_at": "2018-12-30T08:30:32.409Z",
    "pushed_at": "2018-05-10T14:31:15.000Z",
    "homepage": "https://github.com/babel/babel/tree/master/packages/babel-preset-env",
    "size": 1059,
    "stargazers_count": 3520,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 193,
    "mirror_url": null,
    "open_issues_count": 1,
    "default_branch": "1.x",
    "subscribers_count": 65,
    "uuid": "65648767",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 38,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": "Unmaintained",
    "last_synced_at": "2017-09-19T20:39:01.780Z",
    "rank": 18,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "65648767",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 38,
    "keywords": [
      "autoprefixer",
      "babel-preset",
      "es6",
      "javascript",
      "moved"
    ]
  },
  {
    "full_name": "ampproject/amphtml",
    "description": "The AMP web component framework.",
    "fork": false,
    "created_at": "2015-09-01T22:10:53.000Z",
    "updated_at": "2020-04-01T08:17:14.000Z",
    "pushed_at": "2020-04-01T10:21:10.000Z",
    "homepage": "https://amp.dev",
    "size": 705393,
    "stargazers_count": 13552,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 3444,
    "mirror_url": null,
    "open_issues_count": 1891,
    "default_branch": "master",
    "subscribers_count": 694,
    "uuid": "41766002",
    "source_name": null,
    "license": "Apache-2.0",
    "private": false,
    "contributions_count": 598,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-10-28T18:41:54.842Z",
    "rank": 17,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "41766002",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 598,
    "keywords": [

    ]
  },
  {
    "full_name": "malte-wessel/react-custom-scrollbars",
    "description": "React scrollbars component",
    "fork": false,
    "created_at": "2015-08-07T11:53:56.000Z",
    "updated_at": "2019-12-05T23:01:39.513Z",
    "pushed_at": "2019-12-05T06:09:46.000Z",
    "homepage": "http://malte-wessel.github.io/react-custom-scrollbars/",
    "size": 1038,
    "stargazers_count": 2294,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 432,
    "mirror_url": null,
    "open_issues_count": 158,
    "default_branch": "master",
    "subscribers_count": 29,
    "uuid": "40358049",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 21,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": null,
    "has_license": "LICENSE.md",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-12-05T23:01:39.511Z",
    "rank": 17,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "40358049",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 21,
    "keywords": [
      "customizable",
      "react",
      "scrollbars",
      "scrolling"
    ]
  },
  {
    "full_name": "Tencent/wepy",
    "description": "小程序组件化开发框架",
    "fork": false,
    "created_at": "2016-11-14T08:06:56.000Z",
    "updated_at": "2020-04-03T05:24:16.318Z",
    "pushed_at": "2020-04-03T05:23:33.000Z",
    "homepage": "https://wepyjs.github.io/wepy-docs/",
    "size": 7777,
    "stargazers_count": 20001,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 2914,
    "mirror_url": null,
    "open_issues_count": 309,
    "default_branch": "2.0.x",
    "subscribers_count": 742,
    "uuid": "73681508",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 116,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-06-26T08:55:28.516Z",
    "rank": 16,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "73681508",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 116,
    "keywords": [
      "weapp",
      "wepy"
    ]
  },
  {
    "full_name": "handsontable/handsontable",
    "description": "JavaScript/HTML5 Data Grid Component with Spreadsheet Look \u0026 Feel. Available for React, Vue and Angular.",
    "fork": false,
    "created_at": "2011-05-23T22:38:58.000Z",
    "updated_at": "2020-04-03T02:16:31.000Z",
    "pushed_at": "2020-04-02T14:26:36.000Z",
    "homepage": "https://handsontable.com",
    "size": 98650,
    "stargazers_count": 13379,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 2442,
    "mirror_url": null,
    "open_issues_count": 783,
    "default_branch": "master",
    "subscribers_count": 484,
    "uuid": "1790564",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 96,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE.txt",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-04-09T12:19:02.711Z",
    "rank": 16,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "1790564",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 96,
    "keywords": [
      "angular",
      "data-binding",
      "data-grid",
      "data-table",
      "excel",
      "grid-editor",
      "javascript",
      "react",
      "spreadsheet",
      "vue"
    ]
  },
  {
    "full_name": "NervJS/nerv",
    "description": "A blazing fast React alternative, compatible with IE8 and React 16.",
    "fork": false,
    "created_at": "2017-05-07T17:20:01.000Z",
    "updated_at": "2019-11-28T08:50:14.000Z",
    "pushed_at": "2019-11-18T08:04:04.000Z",
    "homepage": "https://nerv.aotu.io",
    "size": 1769,
    "stargazers_count": 4974,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 283,
    "mirror_url": null,
    "open_issues_count": 77,
    "default_branch": "master",
    "subscribers_count": 135,
    "uuid": "90549237",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 15,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": null,
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-05-28T05:50:19.447Z",
    "rank": 16,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "90549237",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 15,
    "keywords": [
      "framework",
      "frontend",
      "inferno",
      "javascript",
      "jsx",
      "nerv",
      "nervjs",
      "preact",
      "react",
      "reactjs",
      "typescript",
      "vdom",
      "virutal-dom"
    ]
  },
  {
    "full_name": "facebookarchive/fixed-data-table",
    "description": "A React table component designed to allow presenting thousands of rows of data.",
    "fork": false,
    "created_at": "2015-01-28T04:19:02.000Z",
    "updated_at": "2019-03-23T00:45:01.000Z",
    "pushed_at": "2019-01-16T02:16:36.000Z",
    "homepage": "http://facebook.github.io/fixed-data-table/",
    "size": 13343,
    "stargazers_count": 4321,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 602,
    "mirror_url": null,
    "open_issues_count": 206,
    "default_branch": "master",
    "subscribers_count": 139,
    "uuid": "29950228",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 43,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-01-03T18:29:34.982Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "29950228",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 43,
    "keywords": [

    ]
  },
  {
    "full_name": "redfin/react-server",
    "description": ":rocket: Blazing fast page load and seamless navigation.",
    "fork": false,
    "created_at": "2016-02-09T19:20:35.000Z",
    "updated_at": "2019-05-21T22:01:36.803Z",
    "pushed_at": "2019-05-21T21:56:53.000Z",
    "homepage": "https://react-server.io/",
    "size": 4324,
    "stargazers_count": 3836,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 208,
    "mirror_url": null,
    "open_issues_count": 138,
    "default_branch": "master",
    "subscribers_count": 77,
    "uuid": "51392574",
    "source_name": null,
    "license": "Apache-2.0",
    "private": false,
    "contributions_count": 72,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-05-21T22:01:36.798Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "51392574",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 72,
    "keywords": [
      "isomorphic",
      "react",
      "react-server",
      "server",
      "ssr",
      "universal"
    ]
  },
  {
    "full_name": "hoodiehq/hoodie",
    "description": ":dog: The Offline First JavaScript Backend",
    "fork": false,
    "created_at": "2012-06-25T10:44:38.000Z",
    "updated_at": "2019-12-20T08:25:22.000Z",
    "pushed_at": "2019-11-08T04:51:55.000Z",
    "homepage": "http://hood.ie",
    "size": 11558,
    "stargazers_count": 3696,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 348,
    "mirror_url": null,
    "open_issues_count": 45,
    "default_branch": "master",
    "subscribers_count": 156,
    "uuid": "4780572",
    "source_name": null,
    "license": "Apache-2.0",
    "private": false,
    "contributions_count": 113,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-11-05T05:13:07.275Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "4780572",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 113,
    "keywords": [
      "backend",
      "hoodie",
      "javascript",
      "offline-first"
    ]
  },
  {
    "full_name": "igorprado/react-notification-system",
    "description": "A complete and totally customizable component for notifications in React",
    "fork": false,
    "created_at": "2015-05-06T12:36:09.000Z",
    "updated_at": "2019-04-19T22:21:50.095Z",
    "pushed_at": "2018-12-12T09:51:36.000Z",
    "homepage": "http://igorprado.github.io/react-notification-system/",
    "size": 3803,
    "stargazers_count": 2295,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 236,
    "mirror_url": null,
    "open_issues_count": 63,
    "default_branch": "master",
    "subscribers_count": 45,
    "uuid": "35157449",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 24,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": null,
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-04-19T22:21:49.992Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "35157449",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 24,
    "keywords": [
      "javascript",
      "notifications",
      "react"
    ]
  },
  {
    "full_name": "AllenFang/react-bootstrap-table",
    "description": "A Bootstrap table built with React.js",
    "fork": false,
    "created_at": "2015-04-11T08:06:37.000Z",
    "updated_at": "2020-01-28T22:09:54.000Z",
    "pushed_at": "2020-02-03T13:31:36.000Z",
    "homepage": "https://allenfang.github.io/react-bootstrap-table/",
    "size": 73438,
    "stargazers_count": 2187,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 783,
    "mirror_url": null,
    "open_issues_count": 413,
    "default_branch": "master",
    "subscribers_count": 88,
    "uuid": "33768009",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 114,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2017-09-04T13:16:08.026Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "33768009",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 114,
    "keywords": [
      "bootstrap-table",
      "react",
      "react-table",
      "table"
    ]
  },
  {
    "full_name": "jsforce/jsforce",
    "description": "Salesforce API Library for JavaScript applications (both on Node.js and web browser)",
    "fork": false,
    "created_at": "2014-01-30T08:56:14.000Z",
    "updated_at": "2020-02-28T19:16:50.000Z",
    "pushed_at": "2020-02-28T22:37:28.000Z",
    "homepage": "http://jsforce.github.io/",
    "size": 31981,
    "stargazers_count": 915,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 382,
    "mirror_url": null,
    "open_issues_count": 313,
    "default_branch": "master",
    "subscribers_count": 76,
    "uuid": "16372438",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 60,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": null,
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-12-15T17:31:55.051Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "16372438",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 60,
    "keywords": [
      "jsforce",
      "salesforce"
    ]
  },
  {
    "full_name": "ArthurClemens/polythene",
    "description": "Material Design component library for Mithril and React",
    "fork": false,
    "created_at": "2015-03-29T17:59:03.000Z",
    "updated_at": "2020-03-23T23:57:38.000Z",
    "pushed_at": "2020-03-23T23:57:36.000Z",
    "homepage": "",
    "size": 268892,
    "stargazers_count": 562,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 42,
    "mirror_url": null,
    "open_issues_count": 1,
    "default_branch": "master",
    "subscribers_count": 22,
    "uuid": "33082960",
    "source_name": null,
    "license": null,
    "private": false,
    "contributions_count": 12,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": null,
    "has_license": null,
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-09-08T14:50:45.189Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "33082960",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 12,
    "keywords": [
      "javascript",
      "material-design",
      "mithril",
      "react"
    ]
  },
  {
    "full_name": "benlesh/symbol-observable",
    "description": "Symbol.observable ponyfill",
    "fork": false,
    "created_at": "2015-11-19T13:31:31.000Z",
    "updated_at": "2019-03-12T00:20:30.000Z",
    "pushed_at": "2018-12-26T12:37:44.000Z",
    "homepage": null,
    "size": 52,
    "stargazers_count": 130,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 25,
    "mirror_url": null,
    "open_issues_count": 4,
    "default_branch": "master",
    "subscribers_count": 10,
    "uuid": "46494071",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 15,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": null,
    "has_license": "license",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2018-01-26T20:35:10.407Z",
    "rank": 15,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "46494071",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 15,
    "keywords": [

    ]
  },
  {
    "full_name": "muicss/mui",
    "description": "Lightweight CSS framework",
    "fork": false,
    "created_at": "2015-02-15T17:30:26.000Z",
    "updated_at": "2020-01-21T07:18:21.000Z",
    "pushed_at": "2020-01-21T07:18:40.000Z",
    "homepage": "https://www.muicss.com",
    "size": 16803,
    "stargazers_count": 4293,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 458,
    "mirror_url": null,
    "open_issues_count": 69,
    "default_branch": "master",
    "subscribers_count": 175,
    "uuid": "30835106",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 30,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": null,
    "has_license": "LICENSE.txt",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-10-10T11:03:52.321Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "30835106",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 30,
    "keywords": [
      "css-framework",
      "google-material",
      "javascript",
      "lightweight-css-framework",
      "material",
      "meteor",
      "mui",
      "nodejs"
    ]
  },
  {
    "full_name": "seatgeek/react-infinite",
    "description": "A browser-ready efficient scrolling container based on UITableView",
    "fork": false,
    "created_at": "2014-10-15T16:26:11.000Z",
    "updated_at": "2018-12-23T22:27:32.000Z",
    "pushed_at": "2018-07-24T12:06:02.000Z",
    "homepage": "",
    "size": 611,
    "stargazers_count": 2531,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 278,
    "mirror_url": null,
    "open_issues_count": 100,
    "default_branch": "master",
    "subscribers_count": 74,
    "uuid": "25263349",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 24,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": null,
    "has_license": "LICENSE.txt",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2018-04-21T17:33:45.421Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "25263349",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 24,
    "keywords": [

    ]
  },
  {
    "full_name": "webiny/webiny-js",
    "description": "Serverless CMS (GraphQL + React + Node.js + AWS Lambda)",
    "fork": false,
    "created_at": "2018-01-09T13:09:44.000Z",
    "updated_at": "2020-04-03T17:04:07.631Z",
    "pushed_at": "2020-04-03T16:54:57.000Z",
    "homepage": "https://www.webiny.com/",
    "size": 125339,
    "stargazers_count": 2055,
    "language": "TypeScript",
    "has_issues": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 157,
    "mirror_url": null,
    "open_issues_count": 83,
    "default_branch": "master",
    "subscribers_count": 45,
    "uuid": "116817549",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 5,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-10-29T11:16:54.784Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "116817549",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 5,
    "keywords": [
      "cms",
      "graphql",
      "javascript",
      "lambda",
      "microservice",
      "nodejs",
      "react",
      "serverless",
      "spa",
      "typescript"
    ]
  },
  {
    "full_name": "schrodinger/fixed-data-table-2",
    "description": "A React table component designed to allow presenting millions of rows of data.",
    "fork": false,
    "created_at": "2016-02-22T17:02:05.000Z",
    "updated_at": "2020-01-23T18:03:56.000Z",
    "pushed_at": "2020-01-15T21:24:22.000Z",
    "homepage": "http://schrodinger.github.io/fixed-data-table-2/",
    "size": 10721,
    "stargazers_count": 1004,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 256,
    "mirror_url": null,
    "open_issues_count": 74,
    "default_branch": "master",
    "subscribers_count": 41,
    "uuid": "52289723",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 89,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-11-28T16:07:53.107Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "52289723",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 89,
    "keywords": [

    ]
  },
  {
    "full_name": "ankeetmaini/react-infinite-scroll-component",
    "description": "An awesome Infinite Scroll component in react.",
    "fork": false,
    "created_at": "2016-03-17T13:28:29.000Z",
    "updated_at": "2020-01-27T16:42:56.345Z",
    "pushed_at": "2020-01-24T16:08:23.000Z",
    "homepage": "https://react-infinite-scroll-component.netlify.com/",
    "size": 2014,
    "stargazers_count": 757,
    "language": "TypeScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 115,
    "mirror_url": null,
    "open_issues_count": 40,
    "default_branch": "master",
    "subscribers_count": 14,
    "uuid": "54119951",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 19,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": null,
    "has_license": "license",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2020-01-27T16:42:56.327Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "54119951",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 19,
    "keywords": [
      "component",
      "infinite-lists",
      "infinite-scroll",
      "npm-package",
      "react"
    ]
  },
  {
    "full_name": "pouchdb/pouchdb-server",
    "description": "CouchDB-compatible server built on PouchDB and Node",
    "fork": false,
    "created_at": "2013-02-01T17:04:19.000Z",
    "updated_at": "2019-09-25T22:12:35.907Z",
    "pushed_at": "2019-09-24T22:49:54.000Z",
    "homepage": "",
    "size": 4818,
    "stargazers_count": 738,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 136,
    "mirror_url": null,
    "open_issues_count": 113,
    "default_branch": "master",
    "subscribers_count": 26,
    "uuid": "7962111",
    "source_name": null,
    "license": "Apache-2.0",
    "private": false,
    "contributions_count": 54,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-09-25T22:12:35.899Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "7962111",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 54,
    "keywords": [

    ]
  },
  {
    "full_name": "facebookarchive/jstransform",
    "description": "A simple utility for pluggable JS syntax transforms using the esprima parser.",
    "fork": false,
    "created_at": "2013-08-05T02:21:00.000Z",
    "updated_at": "2018-12-27T15:31:11.019Z",
    "pushed_at": "2016-08-15T16:20:40.000Z",
    "homepage": "",
    "size": 550,
    "stargazers_count": 466,
    "language": "JavaScript",
    "has_issues": false,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 79,
    "mirror_url": null,
    "open_issues_count": 24,
    "default_branch": "master",
    "subscribers_count": 48,
    "uuid": "11888510",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 29,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": null,
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2017-06-12T16:36:05.948Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "11888510",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 29,
    "keywords": [

    ]
  },
  {
    "full_name": "reactjs/react-lifecycles-compat",
    "description": "Backwards compatibility polyfill for React class components",
    "fork": false,
    "created_at": "2018-01-25T01:36:04.000Z",
    "updated_at": "2019-04-30T01:59:27.000Z",
    "pushed_at": "2018-10-01T15:02:54.000Z",
    "homepage": null,
    "size": 105,
    "stargazers_count": 380,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 27,
    "mirror_url": null,
    "open_issues_count": 3,
    "default_branch": "master",
    "subscribers_count": 14,
    "uuid": "118845765",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 4,
    "has_readme": "README.md",
    "has_changelog": "CHANGELOG.md",
    "has_contributing": null,
    "has_license": "LICENSE.md",
    "has_coc": "CODE_OF_CONDUCT.md",
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2018-04-18T02:47:49.922Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "118845765",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 4,
    "keywords": [
      "api",
      "compatibility",
      "polyfill",
      "react"
    ]
  },
  {
    "full_name": "nbubna/Case",
    "description": "String case utitility: convert, identify, flip, extend",
    "fork": false,
    "created_at": "2013-06-04T18:16:01.000Z",
    "updated_at": "2020-03-24T12:50:59.998Z",
    "pushed_at": "2020-03-24T12:50:13.000Z",
    "homepage": "http://nbubna.github.io/Case/",
    "size": 274,
    "stargazers_count": 217,
    "language": "JavaScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 21,
    "mirror_url": null,
    "open_issues_count": 2,
    "default_branch": "master",
    "subscribers_count": 4,
    "uuid": "10485445",
    "source_name": null,
    "license": "MIT",
    "private": false,
    "contributions_count": 10,
    "has_readme": "README.md",
    "has_changelog": null,
    "has_contributing": "CONTRIBUTING.md",
    "has_license": "LICENSE",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-07-26T21:19:36.985Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "10485445",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 10,
    "keywords": [
      "camelcase",
      "capital",
      "case",
      "constants",
      "dot",
      "javascript",
      "kebab-case",
      "letters",
      "lowercase",
      "pascal",
      "sentence",
      "snake",
      "string",
      "title",
      "type",
      "uppercase"
    ]
  },
  {
    "full_name": "jescalan/accord",
    "description": "a unified interface for compiled languages and templates in javascript",
    "fork": false,
    "created_at": "2013-12-05T00:03:55.000Z",
    "updated_at": "2019-01-21T20:53:38.914Z",
    "pushed_at": "2019-01-21T20:46:18.000Z",
    "homepage": null,
    "size": 711,
    "stargazers_count": 134,
    "language": "CoffeeScript",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 29,
    "mirror_url": null,
    "open_issues_count": 35,
    "default_branch": "master",
    "subscribers_count": 7,
    "uuid": "14939500",
    "source_name": null,
    "license": "Other",
    "private": false,
    "contributions_count": 30,
    "has_readme": "readme.md",
    "has_changelog": null,
    "has_contributing": "contributing.md",
    "has_license": "license.md",
    "has_coc": null,
    "has_threat_model": null,
    "has_audit": null,
    "status": null,
    "last_synced_at": "2019-01-21T20:53:38.911Z",
    "rank": 14,
    "host_type": "GitHub",
    "host_domain": null,
    "name": null,
    "scm": "git",
    "fork_policy": null,
    "github_id": "14939500",
    "pull_requests_enabled": null,
    "logo_url": null,
    "github_contributions_count": 30,
    "keywords": [

    ]
  }
]


module.exports.OPEN_SOURCE_LIBRARIES_PLATFORMS_REPOSITORY = OPEN_SOURCE_LIBRARIES_PLATFORMS_REPOSITORY;
